<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorWasmTemplate.Application\BlazorWasmTemplate.Application.csproj" />
    <ProjectReference Include="..\BlazorWasmTemplate.Domain\BlazorWasmTemplate.Domain.csproj" />
    <ProjectReference Include="..\BlazorWasmTemplate.Infrastructure\BlazorWasmTemplate.Infrastructure.csproj" />
  </ItemGroup>

</Project>
